name: tichu-bot
version: 0.1.0.0
github: "ungrichtepfl/tichu-bot"
license: BSD3
author: "Christoph Ungricht"
maintainer: "christoph.ungricht@outlook.com"
copyright: "2023 Christoph Ungricht"
extra-source-files:
  - README.md
  - CHANGELOG.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ungrichtepfl/tichu-bot#readme>
dependencies:
  - base >= 4.7 && < 5
  - random == 1.2.1.1
  - MonadRandom == 0.5.3
  - tf-random == 0.5
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
library:
  source-dirs: src
executables:
  tichu-bot:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tichu-bot
tests:
  tichu-bot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tichu-bot
