name: tichu-bot
version: 0.1.1.0
github: "ungrichtepfl/tichu-bot"
license: BSD3
author: "Christoph Ungricht"
maintainer: "christoph.ungricht@outlook.com"
copyright: "2023 Christoph Ungricht"
extra-source-files:
  - README.md
  - CHANGELOG.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ungrichtepfl/tichu-bot#readme>
dependencies:
  - base >= 4.7 && < 5
  - random >= 1.2.1.1 && < 2
  - array >= 0.5.4.0 && < 1
  - containers >= 0.6.7 && < 1
  - aeson >= 2.2 && <3
  - bytestring >= 0.12 && < 1
  - scientific >= 0.3 && < 1
  - vector >= 0.13 && < 1
  - monad-loops >= 0.4.3 && < 1
ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-x-partial # Allow functions such as "head"
  - -Wno-orphans # We need to define ToJson for StdGen

library:
  source-dirs: src

executables:
  tichu-cli:
    main: Main.hs
    source-dirs: app/cli
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
      - -Wno-x-partial # Allow functions such as "head"
    dependencies:
      - tichu-bot

  tichu-gui:
    main: Main.hs
    source-dirs: app/gui
    c-sources:
      - cbuild/gui_pp.c
    include-dirs:
      - gui/raylib-5.0/linux_amd64/include
    extra-libraries:
      - :libraylib.a
      - m
    extra-lib-dirs:
      - gui/raylib-5.0/linux_amd64/lib
    cc-options:
      - -O2
      - -Wall
      - -Werror
      - -Wextra
      - -Wpedantic
      - -Wno-overlength-strings
      - -ggdb
      - -std=c23
      - -pedantic
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
    dependencies:
      - tichu-bot

  tichu-wasm:
    main: Main.hs
    source-dirs: ./wasm/app/
    c-sources:
      - ./wasm/app/jsimports.c
    cc-options:
      - -std=c23
    ghc-options:
      - -O2
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
      - -no-hs-main -optl-mexec-model=reactor 
      - -optl-Wl,--export=free
      - -optl-Wl,--export=malloc
    dependencies:
      - ghc-experimental
      - tichu-bot

tests:
  tichu-bot-test:
    main: TestMain.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tichu-bot
      - tasty >= 1.4.3 && < 2
      - tasty-hunit >= 0.10.1 && < 1
